version: '3'

services:
  backend:
    build:
      context: ./../backend
      dockerfile: ./../backend/backend.dockerfile
    restart: always
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1
